# Generated by Django 5.1 on 2024-09-04 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0011_section_pagehindi_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagehindi',
            name='author',
        ),
        migrations.RemoveField(
            model_name='pagehindi',
            name='banner',
        ),
        migrations.RemoveField(
            model_name='pagehindi',
            name='category',
        ),
        migrations.RemoveField(
            model_name='pagehindi',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='pagehindi',
            name='date_updated',
        ),
        migrations.RemoveField(
            model_name='pagehindi',
            name='status',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.RemoveField(
            model_name='post',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='post',
            name='date_updated',
        ),
        migrations.RemoveField(
            model_name='post',
            name='status',
        ),
        migrations.CreateModel(
            name='PageBengali',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('blog_post', models.TextField()),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blogApp.post')),
            ],
        ),
        migrations.CreateModel(
            name='PageMarathi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('blog_post', models.TextField()),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blogApp.post')),
            ],
        ),
        migrations.CreateModel(
            name='PageTamil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('blog_post', models.TextField()),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blogApp.post')),
            ],
        ),
        migrations.DeleteModel(
            name='Page',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
