# Generated by Django 5.1 on 2024-09-12 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0015_remove_post_section_folder_post_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='blogApp.folder'),
        ),
    ]
