# Generated by Django 5.1 on 2024-09-23 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0016_alter_post_folder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='banner',
        ),
        migrations.RemoveField(
            model_name='post',
            name='blog_post',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.AddField(
            model_name='post',
            name='body_content',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='dynamic_table',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='map_img',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='side_panel',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='static_table',
            field=models.JSONField(null=True),
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_file', models.FileField(blank=True, null=True, upload_to='csv_files/')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='blogApp.post')),
            ],
        ),
    ]
