# Generated by Django 5.1 on 2024-09-23 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0017_remove_post_banner_remove_post_blog_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='page_title',
            field=models.CharField(max_length=125, null=True),
        ),
    ]
