# Generated by Django 5.1 on 2024-09-24 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0019_rename_map_img_post_map_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body_content',
            field=models.JSONField(null=True),
        ),
        migrations.DeleteModel(
            name='Table',
        ),
    ]
