# Generated by Django 5.1 on 2024-09-24 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0020_alter_post_body_content_delete_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='page_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
