# Generated by Django 5.1 on 2024-09-24 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0022_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='dynamic_table',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='map_image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='side_panel',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='static_table',
            field=models.TextField(blank=True, null=True),
        ),
    ]
