# Generated by Django 5.1 on 2024-09-24 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0023_alter_post_body_content_alter_post_dynamic_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body_content',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='dynamic_table',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='map_image',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='side_panel',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='static_table',
            field=models.JSONField(null=True),
        ),
    ]
