# Generated by Django 5.1 on 2024-09-25 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0025_alter_post_body_content_alter_post_dynamic_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='static_table',
            field=models.JSONField(null=True),
        ),
    ]
