# Generated by Django 5.1 on 2024-09-25 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0027_alter_post_static_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='static_table',
        ),
    ]
