# Generated by Django 5.1 on 2024-09-25 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0028_remove_post_static_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='static_table',
            field=models.TextField(null=True),
        ),
    ]
