# Generated by Django 5.1 on 2024-09-30 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0029_post_static_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeoAttributesList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_name_description', models.CharField(max_length=1000, null=True)),
                ('meta_name_keywords', models.CharField(max_length=1000, null=True)),
                ('meta_property_og_title', models.CharField(max_length=1000, null=True)),
                ('meta_property_og_url', models.CharField(max_length=1000, null=True)),
                ('meta_property_og_description', models.CharField(max_length=1000, null=True)),
                ('meta_property_og_image', models.CharField(max_length=1000, null=True)),
                ('meta_name_twitter_card', models.CharField(max_length=1000, null=True)),
                ('meta_name_twitter_site', models.CharField(max_length=1000, null=True)),
                ('meta_name_twitter_title', models.CharField(max_length=1000, null=True)),
                ('meta_name_twitter_description', models.CharField(max_length=1000, null=True)),
                ('meta_name_twitter_image_src', models.CharField(max_length=1000, null=True)),
                ('meta_name_viewport', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='seo_attributes',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post', to='blogApp.seoattributeslist'),
        ),
    ]
