# Generated by Django 5.1 on 2024-10-11 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0030_seoattributeslist_post_seo_attributes'),
    ]

    operations = [
        migrations.AddField(
            model_name='seoattributeslist',
            name='canonical',
            field=models.CharField(default='canonical', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='seoattributeslist',
            name='meta_name_description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='seoattributeslist',
            name='meta_name_keywords',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='seoattributeslist',
            name='meta_name_twitter_card',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='seoattributeslist',
            name='meta_name_twitter_description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='seoattributeslist',
            name='meta_name_twitter_image_src',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='seoattributeslist',
            name='meta_name_twitter_site',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='seoattributeslist',
            name='meta_name_twitter_title',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='seoattributeslist',
            name='meta_name_viewport',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='seoattributeslist',
            name='meta_property_og_description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='seoattributeslist',
            name='meta_property_og_image',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='seoattributeslist',
            name='meta_property_og_title',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='seoattributeslist',
            name='meta_property_og_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.CreateModel(
            name='OtherMaps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_name', models.CharField(max_length=200)),
                ('thumbnail', models.ImageField(upload_to='')),
                ('alt', models.CharField(max_length=200)),
                ('redirection_url', models.CharField(blank=True, max_length=255, null=True)),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='blogApp.post')),
            ],
        ),
    ]
